name = "yusu_ke"
main = "src/index.tsx"
compatibility_date = "2024-09-02"

rules = [
  { type = "Text", globs = ["**/*.md"], fallthrough = true }
]

assets = { directory = "./public/" }

routes = [
  { pattern = "yusu.ke/*", zone_id = "caeeeadc7b4bcbe54b3def120f329db6" }
]
